---
  - name: Create a directory /beegfs/mgmtd if it does not exist
    file:
      path: /beegfs/mgmtd
      state: directory
      mode: '0755'
    
  - name: Add a main connection interface for beegfs
    lineinfile:
      path: /etc/beegfs/interfaces
      line: {{ main_beegfs_interface }}
      create: yes
      
  - name: Chnage connInterfacesFile from file
    lineinfile:
      path: /etc/beegfs/beegfs-mgmtd.conf
      regexp: '^connInterfacesFile'
      line: 'connInterfacesFile                     =/etc/beegfs/interfaces'
      
  - name: Chnage connInterfacesFile from file
    lineinfile:
      path: /etc/beegfs/beegfs-client.conf
      regexp: '^connInterfacesFile'
      line: 'connInterfacesFile                     =/etc/beegfs/interfaces'
      
  - name: Chnage connInterfacesFile from file
    lineinfile:
      path: /etc/beegfs/beegfs-meta.conf
      regexp: '^connInterfacesFile'
      line: 'connInterfacesFile                     =/etc/beegfs/interfaces'
      
  - name: Chnage connInterfacesFile from file
    lineinfile:
      path: /etc/beegfs/beegfs-storage.conf
      regexp: '^connInterfacesFile
      line: 'connInterfacesFile                     =/etc/beegfs/interfaces'

  - name: Setup beegfs mgmtd
    command: "/opt/beegfs/sbin/beegfs-setup-mgmtd -f -p /beegfs/mgmtd/"
    ignore_errors: yes

  - name: enable beegfs-mgmtd
    systemd:
      name: beegfs-mgmtd
      state: started
      enabled: yes

  - name: Create a directory /beegfs/meta if it does not exist
    file:
      path: /beegfs/meta
      state: directory
      mode: '0755'

  - name: Setup beegfs mgmtd
    command: "/opt/beegfs/sbin/beegfs-setup-meta -f -p /beegfs/meta/ -m {{ server_host }}"
    ignore_errors: yes

  - name: enable beegfs-meta
    systemd:
      name: beegfs-meta
      state: started
      enabled: yes

  - name: Create a directory /beegfs/storage if it does not exist
    file:
      path: /beegfs/storage
      state: directory
      mode: '0755'

  - name: Setup beegfs mgmtd
    command: "/opt/beegfs/sbin/beegfs-setup-storage -f -p /beegfs/storage/ -m {{ server_host }}"
    ignore_errors: yes

  - name: enable beegfs-storage
    systemd:
      name: beegfs-storage
      state: started
      enabled: yes


  - name: Setup beegfs client
    command: "/opt/beegfs/sbin/beegfs-setup-client -m {{ server_host }}"

  - name: enable beegfs-client
    systemd:
      name: beegfs-client
      state: started
      enabled: yes


