---
  - name: test host ip
    command: "touch /root/{{ server_host }}"
    
  - name: Include "{{ansible_os_family}}" SGE recipe
    include: "{{ansible_os_family}}.yml"

  - name: Include "{{sge_type_of_node}}" SGE recipe
    include: "{{sge_type_of_node}}.yml"
